---
- hosts: localhost
  connection: local
  tasks:
    add_host:
    args:
      hostname: "{{ vm_name }}"

- hosts: "{{ vm_name }}"
  connection: local # only for demo
  tasks:
    - debug:
        msg: "Running second playbook"

